zitadel:
  masterkey: x123456789012345678901234567891y
  configmapConfig:
    ExternalSecure: false
    ExternalDomain: 127.0.0.1.sslip.io
    TLS:
      Enabled: false
    Database:
      Postgres:
        Host: cluster-example-rw
        Port: 5432
        Database: zitadel
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          Username: zitadel
          SSL:
            Mode: verify-full
        Admin:
          Username: postgres
          SSL:
            Mode: verify-full
  secretConfig:
    Database:
      Postgres:
        User:
          Password: xyz
        Admin:
          Password: abc

  dbSslCaCrtSecret: cluster-example-ca 
  dbSslAdminCrtSecret: cluster-example-server
    #dbSslUserCrtSecret: zitadel-cert
