zitadel:
  masterkey: x123456789012345678901234567891y
  debug:
    enabled: false 
  configmapConfig:
    ExternalSecure: true
    ExternalDomain: id.jobico.org 
    ExternalPort: 443
    TLS:
      Enabled: false
    Database:
      Postgres:
        Host: cluster-example-rw
        Port: 5432
        Database: zitadel
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          Username: postgres
          SSL:
            Mode: disable
        Admin:
          Username: postgres
          SSL:
            Mode: disable
  secretConfig:
    Database:
      Postgres:
        User:
          Password: postgres
        Admin:
          Password: postgres
ingress:
  enabled: true
  hosts:
    - host: id.jobico.org 
      paths:
        - path: /
          pathType: Prefix
