# This is the network config written by 'subiquity'
network:
  ethernets:
    enp3s0f0:
      optional: true
      dhcp4: true 
    virbr0:
      routes:
        - to: 10.32.0.0/24
          via: 192.168.122.8
  version: 2
