readonly SCRIPTS="${DIR}/scripts"
readonly ADDONS_DIR="${DIR}/addons"
readonly SERVICES_DIR="${DIR}/services"
readonly EXTRAS_DIR="${DIR}/extras"
readonly MAKE=make
readonly CLUSTER_NAME=jobico-cloud
readonly WORKER_NAME=node
readonly SERVER_NAME=server
readonly LB_NAME=lb
readonly ENCRYPTION_KEY=$(head -c 32 /dev/urandom | base64)
readonly BEGIN_HOSTS_FILE="#B> Kubernetes Cluster"
readonly END_HOSTS_FILE="#E> Kubernetes Cluster"
readonly PLUGINS_CONF_FILE=${DIR}/plugins.conf
readonly DEFAULT_NODES=2
readonly DEFAULT_NODES_ADD=1
readonly DEFAULT_CPL=1
readonly DEFAULT_LB=2
readonly DOMAIN="jobico.local"
readonly DEFAULT_VERS="$DIR/extras/downloads_db/vers.txt"