VM_NAME=ikjumpbox
VM_IP=192.168.122.6
DESIRED_SIZE=20G
mac_vm:=$(shell bash -c 'printf "02:%02x:%02x:%02x:%02x:%02x" $$((RANDOM%256)) $$((RANDOM%256)) $$((RANDOM%256)) $$((RANDOM%256)) $$((RANDOM%256))')
curr_mac=$(shell virsh -q domifaddr ${VM_NAME} --source arp | awk '{print $$2}')

## New VM

new-vm: deploy mac virt 

deploy: debian-12.qcow2 resize cloud-init.cfg cloud-init.iso
	sudo cp debian-12.qcow2  /var/lib/libvirt/boot/debian-12-${VM_NAME}.qcow2 
	sudo cp cloud-init.iso  /var/lib/libvirt/boot/cloud-init-${VM_NAME}.iso 

mac:
	-virsh net-update default add ip-dhcp-host \
	  --xml '<host mac="${mac_vm}" name="${VM_NAME}" ip="${VM_IP}"/>' \
	  --live --config

debian-12.qcow2:
	wget https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
	mv -i debian-12-generic-amd64.qcow2 \
  		debian-12.qcow2

resize: debian-12.qcow2
	qemu-img resize \
  		debian-12.qcow2 \
  		${DESIRED_SIZE} 

cloud-init.cfg cloud-init.iso: 
	sudo cloud-localds cloud-init.iso cloud-init.cfg

virt:
	sudo virt-install \
 		--name ${VM_NAME} \
 		--ram 2048 \
 		--vcpus=1 \
 		--cpu host \
 		--disk /var/lib/libvirt/boot/debian-12-${VM_NAME}.qcow2,device=disk,bus=virtio \
 		--hvm \
 		--disk /var/lib/libvirt/boot/cloud-init-${VM_NAME}.iso,device=cdrom \
 		--os-variant debian10 \
 		--virt-type kvm \
 		--graphics none \
 		--network network=default,model=virtio,mac=${mac_vm}\
 		--import \
 		--noautoconsole
## Destroy the VM

destroy-vm: dhcp-release delete-mac delete-key
	-virsh destroy ${VM_NAME} 
	-virsh undefine ${VM_NAME} --remove-all-storage

dhcp-release:
	-dhcp_release virbr0 ${VM_IP} ${curr_mac}


delete-mac:
	-virsh net-update default delete ip-dhcp-host \
	  '<host ip="${VM_IP}"/>' \
	  --live --config


delete-key:
	-ssh-keygen -f ~/.ssh/known_hosts -R ${VM_IP}

