sudo virt-install \
 --name ${1} \
 --ram 2048 \
 --vcpus=1 \
 --cpu host \
 --disk /var/lib/libvirt/boot/debian-12-${1}.qcow2,device=disk,bus=virtio \
 --hvm \
 --disk /var/lib/libvirt/boot/cloud-init-${1}.iso,device=cdrom \
 --os-variant debian10 \
 --virt-type kvm \
 --graphics none \
 --network network=default,model=virtio,mac=${2}\
 --import \
 --noautoconsole
