version = 3

[plugins."io.containerd.cri.v1.runtime"]
  snapshotter = "overlayfs"
  default_runtime_name = "runc"

  [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.runc]
    runtime_type = "io.containerd.runc.v2"
    
    [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.runc.options]
      SystemdCgroup = true

  [plugins."io.containerd.cri.v1.runtime".cni]
    bin_dir = "/opt/cni/bin"
    conf_dir = "/etc/cni/net.d"