VM_NAME=ikjumpbox
VM_IP=192.168.122.6
LARGE_SIZE=40G
SMALL_SIZE=30G

IMAGE := https://cloud.debian.org/images/cloud/trixie/latest/debian-13-generic-amd64.qcow2

# https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2

HOME_DIR := $(INFRA_DIR)
VM_QCOW2_DIR := $(HOME_DIR)/vm
VM_QCOW2 := $(VM_QCOW2_DIR)/debian-vm.qcow2
VM_QCOW2_LARGE := $(VM_QCOW2_DIR)/debian-13-large.qcow2
VM_QCOW2_SMALL := $(VM_QCOW2_DIR)/debian-13-small.qcow2
VM_QCOW2_BOOT := /var/lib/libvirt/boot/debian-13-$(VM_NAME).qcow2

CFG_CLOUD_INIT_DIR := $(HOME_DIR)/cfg
CFG_CLOUD_INIT := $(CFG_CLOUD_INIT_DIR)/cloud-init-node.cfg
CFG_CLOUD_INIT_CGROUPV1 := $(CFG_CLOUD_INIT_DIR)/cloud-init-node-cgroupv1.cfg
CFG_CLOUD_INIT_LB := $(CFG_CLOUD_INIT_DIR)/cloud-init-lb.cfg

CFG_CLOUD_ISO_DIR := $(HOME_DIR)/iso
CFG_CLOUD_ISO := $(CFG_CLOUD_ISO_DIR)/cloud-init-node.iso
CFG_CLOUD_ISO_LB := $(CFG_CLOUD_ISO_DIR)/cloud-init-lb.iso
CFG_CLOUD_ISO_CGROUPV1 := $(CFG_CLOUD_ISO_DIR)/cloud-init-node-cgroupv1.iso
CFG_CLOUD_ISO_BOOT := /var/lib/libvirt/boot/cloud-init-$(VM_NAME).iso

CMD=start
MAC_VM := $(shell bash -c 'printf "02:%02x:%02x:%02x:%02x:%02x" $$((RANDOM%256)) $$((RANDOM%256)) $$((RANDOM%256)) $$((RANDOM%256)) $$((RANDOM%256))')
CURR_MAC := $(shell virsh -q domifaddr $(VM_NAME) --source arp | awk '{print $$2}')

## New VM

new-vm-cgroupv2-node: $(CFG_CLOUD_ISO_DIR) $(VM_QCOW2_DIR) deploy-cgroupv2-node mac virt-node 

new-vm-cgroupv2-sm-node: $(CFG_CLOUD_ISO_DIR) $(VM_QCOW2_DIR) deploy-cgroupv2-sm-node mac virt-2cpu-2gb-node

new-vm-cgroupv1-node: $(CFG_CLOUD_ISO_DIR) $(VM_QCOW2_DIR) deploy-cgroupv1-node mac virt-node

new-vm-cgroupv1-sm-node: $(CFG_CLOUD_ISO_DIR) $(VM_QCOW2_DIR) deploy-cgroupv1-sm-node mac virt-2cpu-2gb-node

new-vm-cgroupv2-server: $(CFG_CLOUD_ISO_DIR) $(VM_QCOW2_DIR) deploy-server mac virt-node 

new-vm-cgroupv2-lb: $(CFG_CLOUD_ISO_DIR) $(VM_QCOW2_DIR) deploy-lb mac virt-lb 

$(CFG_CLOUD_ISO_DIR): 
	mkdir -p $@

$(VM_QCOW2_DIR):
	mkdir -p $@

deploy-cgroupv2-node: $(VM_QCOW2) $(VM_QCOW2_LARGE) $(CFG_CLOUD_INIT) $(CFG_CLOUD_ISO)
	sudo cp $(VM_QCOW2_LARGE) $(VM_QCOW2_BOOT)
	sudo cp $(CFG_CLOUD_ISO) $(CFG_CLOUD_ISO_BOOT)

deploy-cgroupv2-sm-node: $(VM_QCOW2) $(VM_QCOW2_SMALL) $(CFG_CLOUD_INIT) $(CFG_CLOUD_ISO)
	sudo cp $(VM_QCOW2_SMALL) $(VM_QCOW2_BOOT)
	sudo cp $(CFG_CLOUD_ISO) $(CFG_CLOUD_ISO_BOOT)

deploy-cgroupv1-sm-node: $(VM_QCOW2) $(VM_QCOW2_SMALL) $(CFG_CLOUD_INIT_CGROUPV1) $(CFG_CLOUD_ISO_CGROUPV1)
	sudo cp $(VM_QCOW2_SMALL) $(VM_QCOW2_BOOT)
	sudo cp $(CFG_CLOUD_ISO_CGROUPV1)  $(CFG_CLOUD_ISO_BOOT) 

deploy-cgroupv1-node: $(VM_QCOW2) $(VM_QCOW2_LARGE) $(CFG_CLOUD_INIT_CGROUPV1) $(CFG_CLOUD_ISO_CGROUPV1)
	sudo cp $(VM_QCOW2_LARGE) $(VM_QCOW2_BOOT)
	sudo cp $(CFG_CLOUD_ISO_CGROUPV1)  $(CFG_CLOUD_ISO_BOOT) 


deploy-server: $(VM_QCOW2) $(VM_QCOW2_LARGE) $(CFG_CLOUD_INIT) $(CFG_CLOUD_ISO)
	sudo cp $(VM_QCOW2_LARGE) $(VM_QCOW2_BOOT)
	sudo cp $(CFG_CLOUD_ISO)  $(CFG_CLOUD_ISO_BOOT) 

deploy-lb: $(VM_QCOW2) $(VM_QCOW2_LARGE) $(CFG_CLOUD_INIT_LB) $(CFG_CLOUD_ISO_LB)
	sudo cp $(VM_QCOW2_LARGE) $(VM_QCOW2_BOOT)
	sudo cp $(CFG_CLOUD_ISO_LB)  $(CFG_CLOUD_ISO_BOOT) 

mac:
	-virsh net-update default add ip-dhcp-host \
	  --xml '<host mac="$(MAC_VM)" name="$(VM_NAME)" ip="$(VM_IP)" />' \
	  --live --config

$(VM_QCOW2):
	wget -O $@.tmp $(IMAGE) && mv $@.tmp $@
	
$(VM_QCOW2_LARGE):	
	cp $(VM_QCOW2) \
  		$@
	qemu-img resize \
  		$@ \
  		$(LARGE_SIZE)

$(VM_QCOW2_SMALL):
	cp $(VM_QCOW2) \
  		$@
	qemu-img resize \
  		$@ \
  		$(SMALL_SIZE)

cmd-vm:
	-virsh $(CMD) $(VM_NAME)

list:
	-virsh list --all

$(CFG_CLOUD_INIT_LB) $(CFG_CLOUD_ISO_LB): 
	sudo cloud-localds $(CFG_CLOUD_ISO_LB) $(CFG_CLOUD_INIT_LB)

$(CFG_CLOUD_INIT) $(CFG_CLOUD_ISO): 
	sudo cloud-localds $(CFG_CLOUD_ISO) $(CFG_CLOUD_INIT)

$(CFG_CLOUD_INIT_CGROUPV1) $(CFG_CLOUD_ISO_CGROUPV1): 
	sudo cloud-localds $(CFG_CLOUD_ISO_CGROUPV1) $(CFG_CLOUD_INIT_CGROUPV1)


virt-node:
	sudo virt-install \
		--name $(VM_NAME) \
		--ram 6144 \
		--vcpus=3 \
		--cpu host \
		--disk $(VM_QCOW2_BOOT),device=disk,bus=virtio \
		--boot uefi \
		--disk $(CFG_CLOUD_ISO_BOOT),device=cdrom \
		--os-variant debian12 \
		--virt-type kvm \
		--graphics none \
		--console pty,target_type=serial \
		--network network=default,model=virtio,mac=$(MAC_VM) \
		--import \
		--noautoconsole
		
virt-node-cgroupv1:
	sudo virt-install \
 		--name $(VM_NAME) \
 		--ram 4096 \
 		--vcpus=2 \
 		--cpu host \
 		--disk $(VM_QCOW2_BOOT),device=disk,bus=virtio \
 		--hvm \
 		--disk $(CFG_CLOUD_ISO_BOOT),device=cdrom \
 		--os-variant debian10 \
 		--virt-type kvm \
 		--graphics none \
 		--network network=default,model=virtio,mac=$(MAC_VM)\
		--extra-args="systemd.unified_cgroup_hierarchy=0" \
 		--import \
 		--noautoconsole


virt-2cpu-2gb-node:
	sudo virt-install \
 		--name $(VM_NAME) \
 		--ram 2048 \
 		--vcpus=2 \
 		--cpu host \
 		--disk $(VM_QCOW2_BOOT),device=disk,bus=virtio \
 		--hvm \
 		--disk $(CFG_CLOUD_ISO_BOOT),device=cdrom \
 		--os-variant debian10 \
 		--virt-type kvm \
 		--graphics none \
 		--network network=default,model=virtio,mac=$(MAC_VM)\
 		--import \
 		--noautoconsole

virt-2cpu-2gb-node-cgroupv1:
	sudo virt-install \
 		--name $(VM_NAME) \
 		--ram 2048 \
 		--vcpus=2 \
 		--cpu host \
 		--disk $(VM_QCOW2_BOOT),device=disk,bus=virtio \
 		--hvm \
 		--disk $(CFG_CLOUD_ISO_BOOT),device=cdrom \
 		--os-variant debian10 \
 		--virt-type kvm \
 		--graphics none \
 		--network network=default,model=virtio,mac=$(MAC_VM)\
		--extra-args="systemd.unified_cgroup_hierarchy=0" \
 		--import \
 		--noautoconsole

virt-lb:
	sudo virt-install \
 		--name $(VM_NAME) \
 		--ram 2048 \
 		--vcpus=1 \
 		--cpu host \
 		--disk $(VM_QCOW2_BOOT),device=disk,bus=virtio \
 		--hvm \
 		--disk $(CFG_CLOUD_ISO_BOOT),device=cdrom \
 		--os-variant debian10 \
 		--virt-type kvm \
 		--graphics none \
 		--network network=default,model=virtio,mac=$(MAC_VM)\
 		--import \
 		--noautoconsole
## Destroy the VM

destroy-vm: delete-mac delete-key
	-virsh destroy $(VM_NAME) 
	-virsh undefine $(VM_NAME) --remove-all-storage --nvram

delete-mac:
	-virsh net-update default delete ip-dhcp-host \
	  '<host ip="$(VM_IP)"/>' \
	  --live --config


delete-key:
	-ssh-keygen -f ~/.ssh/known_hosts -R $(VM_IP)
	-ssh-keygen -f ~/.ssh/known_hosts -R $(VM_NAME)

