VM_NAME=ikjumpbox
VM_IP=192.168.122.6
LARGE_SIZE=40G
SMALL_SIZE=30G
CMD=start
mac_vm:=$(shell bash -c 'printf "02:%02x:%02x:%02x:%02x:%02x" $$((RANDOM%256)) $$((RANDOM%256)) $$((RANDOM%256)) $$((RANDOM%256)) $$((RANDOM%256))')
curr_mac=$(shell virsh -q domifaddr ${VM_NAME} --source arp | awk '{print $$2}')

## New VM

new-vm-cgroupv2-node: iso vm deploy-cgroupv2-node mac virt-node 

new-vm-cgroupv2-sm-node: iso vm deploy-cgroupv2-sm-node mac virt-2cpu-2gb-node

new-vm-cgroupv1-node: iso vm deploy-cgroupv1-node mac virt-node

new-vm-cgroupv1-sm-node: iso vm deploy-cgroupv1-sm-node mac virt-2cpu-2gb-node

new-vm-cgroupv2-server: iso vm deploy-server mac virt-node 

new-vm-cgroupv2-lb: iso vm deploy-lb mac virt-lb 

iso: 
	mkdir -p iso
vm:
	mkdir -p vm



deploy-cgroupv2-node: vm/debian-vm.qcow2 vm/debian-12-large.qcow2 extras/cfg/cloud-init-node.cfg iso/cloud-init-node.iso
	sudo cp vm/debian-12-large.qcow2 /var/lib/libvirt/boot/debian-12-${VM_NAME}.qcow2 
	sudo cp iso/cloud-init-node.iso  /var/lib/libvirt/boot/cloud-init-${VM_NAME}.iso 

deploy-cgroupv2-sm-node: vm/debian-vm.qcow2 vm/debian-12-small.qcow2 extras/cfg/cloud-init-node.cfg iso/cloud-init-node.iso
	sudo cp vm/debian-12-small.qcow2  /var/lib/libvirt/boot/debian-12-${VM_NAME}.qcow2 
	sudo cp iso/cloud-init-node.iso  /var/lib/libvirt/boot/cloud-init-${VM_NAME}.iso

deploy-cgroupv1-sm-node: vm/debian-vm.qcow2 vm/debian-12-small.qcow2 extras/cfg/cloud-init-node-cgroupv1.cfg iso/cloud-init-node-cgroupv1.iso
	sudo cp vm/debian-12-small.qcow2  /var/lib/libvirt/boot/debian-12-${VM_NAME}.qcow2 
	sudo cp iso/cloud-init-node-cgroupv1.iso  /var/lib/libvirt/boot/cloud-init-${VM_NAME}.iso 

deploy-cgroupv1-node: vm/debian-vm.qcow2 vm/debian-12-large.qcow2 extras/cfg/cloud-init-node-cgroupv1.cfg iso/cloud-init-node-cgroupv1.iso
	sudo cp vm/debian-12-large.qcow2  /var/lib/libvirt/boot/debian-12-${VM_NAME}.qcow2 
	sudo cp iso/cloud-init-node-cgroupv1.iso  /var/lib/libvirt/boot/cloud-init-${VM_NAME}.iso 


deploy-server: vm/debian-vm.qcow2 vm/debian-12-large.qcow2 extras/cfg/cloud-init-node.cfg iso/cloud-init-node.iso
	sudo cp vm/debian-12-large.qcow2  /var/lib/libvirt/boot/debian-12-${VM_NAME}.qcow2 
	sudo cp iso/cloud-init-node.iso  /var/lib/libvirt/boot/cloud-init-${VM_NAME}.iso 

deploy-lb: vm/debian-vm.qcow2 vm/debian-12-small.qcow2 extras/cfg/cloud-init-lb.cfg iso/cloud-init-lb.iso
	sudo cp vm/debian-12-small.qcow2  /var/lib/libvirt/boot/debian-12-${VM_NAME}.qcow2 
	sudo cp iso/cloud-init-lb.iso  /var/lib/libvirt/boot/cloud-init-${VM_NAME}.iso 

mac:
	-virsh net-update default add ip-dhcp-host \
	  --xml '<host mac="${mac_vm}" name="${VM_NAME}" ip="${VM_IP}"/>' \
	  --live --config

vm/debian-vm.qcow2:
	wget -O vm/debian-vm.qcow2 https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
	
vm/debian-12-large.qcow2:	
	cp vm/debian-vm.qcow2 \
  		vm/debian-12-large.qcow2
	qemu-img resize \
  		vm/debian-12-large.qcow2 \
  		${LARGE_SIZE}

vm/debian-12-small.qcow2:
	cp vm/debian-vm.qcow2 \
  		vm/debian-12-small.qcow2
	qemu-img resize \
  		vm/debian-12-small.qcow2 \
  		${SMALL_SIZE}

cmd-vm:
	-virsh ${CMD} ${VM_NAME}

list:
	-virsh list --all

extras/cfg/cloud-init-lb.cfg iso/cloud-init-lb.iso: 
	sudo cloud-localds iso/cloud-init-lb.iso extras/cfg/cloud-init-lb.cfg

extras/cfg/cloud-init-node.cfg iso/cloud-init-node.iso: 
	sudo cloud-localds iso/cloud-init-node.iso extras/cfg/cloud-init-node.cfg

extras/cfg/cloud-init-node-cgroupv1.cfg iso/cloud-init-node-cgroupv1.iso: 
	sudo cloud-localds iso/cloud-init-node-cgroupv1.iso extras/cfg/cloud-init-node-cgroupv1.cfg


virt-node:
	sudo virt-install \
 		--name ${VM_NAME} \
 		--ram 4096 \
 		--vcpus=2 \
 		--cpu host \
 		--disk /var/lib/libvirt/boot/debian-12-${VM_NAME}.qcow2,device=disk,bus=virtio \
 		--hvm \
 		--disk /var/lib/libvirt/boot/cloud-init-${VM_NAME}.iso,device=cdrom \
 		--os-variant debian10 \
 		--virt-type kvm \
 		--graphics none \
 		--network network=default,model=virtio,mac=${mac_vm}\
 		--import \
 		--noautoconsole

virt-node-cgroupv1:
	sudo virt-install \
 		--name ${VM_NAME} \
 		--ram 4096 \
 		--vcpus=2 \
 		--cpu host \
 		--disk /var/lib/libvirt/boot/debian-12-${VM_NAME}.qcow2,device=disk,bus=virtio \
 		--hvm \
 		--disk /var/lib/libvirt/boot/cloud-init-${VM_NAME}.iso,device=cdrom \
 		--os-variant debian10 \
 		--virt-type kvm \
 		--graphics none \
 		--network network=default,model=virtio,mac=${mac_vm}\
		--extra-args="systemd.unified_cgroup_hierarchy=0" \
 		--import \
 		--noautoconsole


virt-2cpu-2gb-node:
	sudo virt-install \
 		--name ${VM_NAME} \
 		--ram 2048 \
 		--vcpus=2 \
 		--cpu host \
 		--disk /var/lib/libvirt/boot/debian-12-${VM_NAME}.qcow2,device=disk,bus=virtio \
 		--hvm \
 		--disk /var/lib/libvirt/boot/cloud-init-${VM_NAME}.iso,device=cdrom \
 		--os-variant debian10 \
 		--virt-type kvm \
 		--graphics none \
 		--network network=default,model=virtio,mac=${mac_vm}\
 		--import \
 		--noautoconsole

virt-2cpu-2gb-node-cgroupv1:
	sudo virt-install \
 		--name ${VM_NAME} \
 		--ram 2048 \
 		--vcpus=2 \
 		--cpu host \
 		--disk /var/lib/libvirt/boot/debian-12-${VM_NAME}.qcow2,device=disk,bus=virtio \
 		--hvm \
 		--disk /var/lib/libvirt/boot/cloud-init-${VM_NAME}.iso,device=cdrom \
 		--os-variant debian10 \
 		--virt-type kvm \
 		--graphics none \
 		--network network=default,model=virtio,mac=${mac_vm}\
		--extra-args="systemd.unified_cgroup_hierarchy=0" \
 		--import \
 		--noautoconsole

virt-lb:
	sudo virt-install \
 		--name ${VM_NAME} \
 		--ram 2048 \
 		--vcpus=1 \
 		--cpu host \
 		--disk /var/lib/libvirt/boot/debian-12-${VM_NAME}.qcow2,device=disk,bus=virtio \
 		--hvm \
 		--disk /var/lib/libvirt/boot/cloud-init-${VM_NAME}.iso,device=cdrom \
 		--os-variant debian10 \
 		--virt-type kvm \
 		--graphics none \
 		--network network=default,model=virtio,mac=${mac_vm}\
 		--import \
 		--noautoconsole
## Destroy the VM

destroy-vm: delete-mac delete-key
	-virsh destroy ${VM_NAME} 
	-virsh undefine ${VM_NAME} --remove-all-storage

delete-mac:
	-virsh net-update default delete ip-dhcp-host \
	  '<host ip="${VM_IP}"/>' \
	  --live --config


delete-key:
	-ssh-keygen -f ~/.ssh/known_hosts -R ${VM_IP}
	-ssh-keygen -f ~/.ssh/known_hosts -R ${VM_NAME}

