apiVersion: v1
kind: Pod
metadata:
  name: docker-registry-pod
  labels:
    app: registry
spec:
  containers:
    - name: registry
      image: registry:2.6.2
      volumeMounts:
        - name: repo-vol
          mountPath: "/var/lib/registry"
        - name: auth-vol
          mountPath: "/auth"
          readOnly: true
      env:
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/htpasswd"
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/certs/tls.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/certs/tls.key"
  volumes:
    - name: repo-vol
      persistentVolumeClaim:
        claimName: docker-repo-pvc
    - name: auth-vol
      secret:
        secretName: auth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  selector:
    app: registry
  clusterIP: 10.32.0.200
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  type: LoadBalancer
  selector:
    app: registry
  ports:
    - name: "def"
      port: 5000
      targetPort: 5000
    - name: "https"
      port: 443
      targetPort: 5000
    - name: "http"
      port: 80
      targetPort: 5000
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: docker-registry-ingress
spec:
    tls:
    - hosts:
      - reg.jobico.org
    rules:
    - host: reg.jobico.org
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: registry
              port: 
                name: https
